#!/usr/bin/env bash
# vi: ft=bash

set -euf -o pipefail

for dropin in work personal
do
        if [[ -d "${dropin}" ]]
        then
                echo Drop-in ${dropin} already exists, skipping
        else
                mkdir -p ${dropin}
                echo "{ ... }: {}" > ${dropin}/home.nix
                echo "{ ... }: {}" > ${dropin}/configuration.nix
                echo "{ ... }: {}" > ${dropin}/printing.nix
                echo "[]" > ${dropin}/printers.nix
                echo "pkgs: with pkgs; []" > ${dropin}/packages.nix
                echo "================================================================"
                echo "Created stub directory for your ${dropin} configurations. At a later point"
                echo "you can backup and symlink in prefered ${dropin} configurations. Ex:"
                echo "    cd ~/.config/nixpgs"
                echo "    mv ${dropin} ${dropin}.bak"
                echo "    ln -s ~/Projects/nix-home-${dropin} ${dropin}"
                echo "================================================================"
        fi
done

if [[ ! -f printing.nix ]]; then
        echo "linking $PWD/examples/printing.nix to $PWD/printing.nix"
        ln -s $PWD/examples/printing.nix $PWD/printing.nix
else
        echo $PWD/printing.nix already exists, skipping
fi

if [[ ! -f $PWD/desktop-manager.nix ]]; then
        echo linking $PWD/desktop-manager/xmonad.nix to $PWD/desktop-manager.nix
        ln -s $PWD/desktop-manager/xmonad.nix $PWD/desktop-manager.nix
else
        echo $PWD/desktop-manager.nix already exists, skipping
fi

# Uncomment the following if you'd like to enable RT kernel from musnix
# sudo nix-channel --add https://github.com/musnix/musnix/archive/master.tar.gz musnix
# sudo nix-channel --update musnix
